#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-seostudio-airequestprocessor-oahs.oauth2.headless.server.client.secret=${LIFERAY_SEOSTUDIO_AIREQUESTPROCESSOR_OAHS_CLIENT_SECRET:}

liferay.oauth.application.external.reference.codes=\
    liferay-seostudio-airequestprocessor-oahs,\
    liferay-seostudio-airequestprocessor-oaua
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081

spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB